esphome:
  name: Power Intercooler

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
 - platform: esphome
   password: "this will autofill with new device"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Power Intercooler-AP"
    password: ""this will autofill with new device"

sensor:
  - platform: dht
    pin: GPIO14
    model: DHT22
    temperature:
      name: "Power Core Temp"
    humidity:
      name: "Power Core Humidity"
    update_interval: 60s

switch:
  - platform: gpio
    name: "fanRelay"
    pin: GPIO5

captive_portal:
